version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka1:
    image: confluentinc/cp-kafka:6.1.1
    container_name: kafka1
    ports:
      - 19092:19092
      - 19094:19094
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:19092,OUTSIDE://:19094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,OUTSIDE://host.docker.internal:19094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - host.docker.internal:172.17.0.1 #Gateway do docker

  kafka2:
    image: confluentinc/cp-kafka:6.1.1
    container_name: kafka2
    ports:
      - 29092:29092
      - 29094:29094
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:29092,OUTSIDE://:29094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:29092,OUTSIDE://host.docker.internal:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - host.docker.internal:172.17.0.1 #Gateway do docker

  kafka-topics-generator:
    image: confluentinc/cp-kafka:6.1.1
    container_name: kafka-topics-generator
    depends_on:
      - kafka1
      - kafka2
    command: >
      bash -c
        "
          sleep 5s &&
          kafka-topics --create --topic=loja.novo-pedido --if-not-exists --replication-factor=2 --bootstrap-server=kafka1:19092
        "
